###  Data Cleaning and Preprocessing 

This notebook focuses on cleaning and preparing a dataset for analysis.The main goal is to ensure the data is accurate, consistent, and ready for further exploratory analysis or modelling.

###  Objectives
The dataset was imported from a CSV file and processed to address common data quality issues, including:
- duplicate records
- missing values
- null values
- inconsistent column naming
- formatting inconsistencies

In [34]:
#Load the data
import pandas as pd 

df= pd.read_csv('heart.csv.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

#### Handling Duplicates

Duplicates rows were identified and removed to avoid skewed results and inaccurate analysis.

In [35]:
# Check for duplicated rows
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
298    False
299    False
300    False
301    False
302    False
Length: 303, dtype: bool

In [36]:
# How many duplicated rows are there?
df.duplicated().sum()

np.int64(1)

In [37]:
# View the duplicated rows
df[df.duplicated()]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
164,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1

In [38]:
# drop the duplicated rows
df = df.drop_duplicates()

In [39]:
df.shape

(302, 14)

#### Handling Missing Values

In [40]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

###     Filtering rows 

Columns were reviewed to ensure that values were standardized to improve readability and consistency.

In [41]:
# Check for outliers in the "chol" column
df[df["chol"]>400]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2,1
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3,1
220,63,0,0,150,407,0,0,154,0,4.0,1,3,3,0
246,56,0,0,134,409,0,0,150,1,1.9,1,2,3,0

### Creating labelled axes 

Replaced the names amd labels with the right ones for sex, target, and exang.

In [42]:
# using .map()
df["sex_label"] = df["sex"].map({1: "Male", 0: "Female"})

In [43]:
#check the first few rows of the dataframe to see the new column
df[["sex", "sex_label"]].head()

   sex sex_label
0    1      Male
1    1      Male
2    0    Female
3    1      Male
4    0    Female

In [45]:
#using .map()
df["target_label"] = df["target"].map({0: "Heart Disease", 1: "No Heart Disease"})
df["has_disease"] = 1 - df["target"]

In [46]:
#check the first few rows of the dataframe to see the new column
df[["target", "target_label","has_disease"]].head()

   target      target_label  has_disease
0       1  No Heart Disease            0
1       1  No Heart Disease            0
2       1  No Heart Disease            0
3       1  No Heart Disease            0
4       1  No Heart Disease            0

In [47]:
#using .map()
df["exang_label"] = df["exang"].map({1: "Yes", 0: "No"})
#check the first few rows of the dataframe to see the new column
df[["exang", "exang_label"]].head()

   exang exang_label
0      0          No
1      0          No
2      0          No
3      0          No
4      1         Yes

In [48]:
#new table with the new columns
df_new = df[["sex_label", "target_label", "exang_label"]]
df_new.head()

  sex_label      target_label exang_label
0      Male  No Heart Disease          No
1      Male  No Heart Disease          No
2    Female  No Heart Disease          No
3      Male  No Heart Disease          No
4    Female  No Heart Disease         Yes

In [49]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,sex_label,target_label,has_disease,exang_label
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,Male,No Heart Disease,0,No
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,Male,No Heart Disease,0,No
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1,Female,No Heart Disease,0,No
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1,Male,No Heart Disease,0,No
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1,Female,No Heart Disease,0,Yes

### Saving 

This cleaning process improved the quality of the dataset by:

removing duplicate records
reducing inconsistencies caused by missing and null values
ensuring consistent and readable column names
preparing the data for reliable analysis

In [50]:
#saving the cleaned data to a new csv file
df.to_csv('heart_cleaned.csv', index=False)